### PR TITLE
New Contribution

### PR DESCRIPTION
**Pull request by gachillea**
## Pull Request Checklist

Thank you for contributing to the Budget Tracker project! Please complete the following checklist to help us ensure your changes are well-documented and fit into the project smoothly.

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [ ] I have commented on my code where applicable, especially in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings or errors.
- [ ] I have added tests that prove my fix or feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Description

Please describe your changes and what issue this addresses: I added a new window for register, so that the user does not have to put the new name and password in the loginWindow. Also I changed the way the date is being put in the expenses and income. Now the date is not entered by the user, but is entered automatically the current date. This way there are no errors in the format.

Fixes #

## Type of Change

- [x] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Documentation update
- [x] Refactoring

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes:

- [ ] Unit tests
- [x] Manual testing
- [ ] Other (please specify)

### CODE REVIEW

**Comment by gachillea** [comment]
If you liked my contribution you can tell me, so that we can cooperate more in the future

**Comment by gachillea** [comment]
Also I apologise for the mistake, the BudgetTracker.py is the same with the main.py I commited

**Comment by SpreadSheets600** [comment]
@gachillea no offence, but what exactly did you do ?

**Comment by gachillea** [comment]
> @gachillea no offence, but what exactly did you do ?

First, I made a new window for register. Now at the login window, when the user presses the "register" button, it opens another window to write the name and password of the new user. And also when someone enters a new Income or Expense, they do not have to write the date when it happens, because the current date is entered by the programm.
At this point I would like to state that I am new in all the github contributions so I may do some things wrong in the procedure. However, I have programming skills and you can tell me if you need some specific changes to be done from me. Anything you want in the app.

**Comment by SpreadSheets600** [comment]
@gachillea thanks for the amazing changes 😄

**Comment by gachillea** [comment]
@SpreadSheets600 is there something else you would like help with?

**Comment by SpreadSheets600** [comment]
> @SpreadSheets600 is there something else you would like help with?

There are a few issues opened up, you can work on them. You can always come up with something you want :)

**Pull request merged**
