### PR TITLE
Added export to csv feature, enhanced visualtisation capabilities

### PR DESCRIPTION
**Pull request by NAMAN9801**
## Pull Request Checklist

Thank you for contributing to the Budget Tracker project! Please complete the following checklist to help us ensure your changes are well-documented and fit into the project smoothly.

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my code.
- [ ] I have commented on my code where applicable, especially in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings or errors.
- [ ] I have added tests that prove my fix or feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Description
Added export csv function.
enhanced functionality and dependencies 
enhanced UI UX experience

Please describe your changes and what issue this addresses:

Fixes #

## Type of Change
New Feature

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update
- [ ] Refactoring

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes:
Manual Testing

- [ ] Unit tests
- [ ] Manual testing
- [ ] Other (please specify)

### CODE REVIEW

**Comment by SpreadSheets600** [comment]
@NAMAN9801 thank you for your amazing contribution

**Comment by NAMAN9801** [comment]
Screenshot 2024-10-13 225623

Sir, I am participating in Hacktober fest, here i have uploaded the screenshot of my this pull req. you have merged this into the main branch but it is showing that it was not accepted. Can you please help me resolve this issue?

**Comment by NAMAN9801** [comment]
Sir, I am participating in Hacktober fest, here i have uploaded the
screenshot of my this pull req. you have merged this into the main branch
but it is showing that it was not accepted. Can you please help me resolve
this issue[image: Screenshot 2024-10-13 225623.png]

**Comment by SpreadSheets600** [comment]
@NAMAN9801 sorry, the reason it was not because I forgot to put the tag, now I did and it will update.

**Comment by NAMAN9801** [comment]
Thank you!!

**Pull request merged**
